// ---------------------------
// This file was generated by Nango (v0.69.16)
// You can version this file
// ---------------------------

export interface SyncMetadata_slack_users {
};

export interface SlackUser {
  id: string;
  team_id: string;
  name: string;
  deleted: boolean;
  tz: string;
  tz_label: string;
  tz_offset: number;
  profile: {  avatar_hash: string;
  real_name: string | null;
  display_name: string | null;
  real_name_normalized: string | null;
  display_name_normalized: string | null;
  email: string | null;
  image_original: string | null;};
  is_admin: boolean;
  is_owner: boolean;
  is_primary_owner: boolean;
  is_restricted: boolean;
  is_ultra_restricted: boolean;
  is_bot: boolean;
  updated: number;
  is_app_user: boolean;
  raw_json: string;
};

export interface ActionInput_slack_sendmessage {
  channel: string;
  text: string;
};

export interface ActionOutput_slack_sendmessage {
  ok: boolean;
  channel?: string | undefined;
  ts?: string | undefined;
  message?: string | undefined;
  warning?: string | undefined;
  error?: string | undefined;
  raw_json: string;
};

export interface SyncMetadata_google_drive_documents {
  files: string[];
  folders: string[];
};

export interface Document {
  id: string;
  url: string;
  title: string;
  mimeType: string;
  updatedAt: string;
};

export interface ActionInput_google_drive_fetchdocument {
  id: string;
};

export type ActionOutput_google_drive_fetchdocument = string

export interface SyncMetadata_one_drive_userfilesselection {
  drives: string[];
  pickedFiles: ({  driveId: string;
  fileIds: string[];})[];
};

export interface OneDriveFileSelection {
  id: string;
  name: string;
  etag: string;
  cTag: string;
  is_folder: boolean;
  mime_type: string | null;
  path: string;
  raw_source: {};
  updated_at: string;
  created_at: string;
  blob_size: number;
  drive_id: string;
};

export interface ActionInput_one_drive_fetchfile {
  driveId: string;
  itemId: string;
};

export interface ActionOutput_one_drive_fetchfile {
  id: string;
  download_url: string | null;
};

export interface SyncMetadata_one_drive_personal_userfilesselection {
  fileIds: string[];
};

export interface SyncMetadata_jira_projects {
  projectIdsToSync: ({  id: string;})[];
  cloudId?: string | undefined;
  baseUrl?: string | undefined;
  timeZone?: string | undefined;
};

export interface Project {
  id: string;
  key: string;
  name: string;
  url: string;
  projectTypeKey: string;
  webUrl: string;
};

export interface SyncMetadata_jira_issuetypes {
  projectIdsToSync: ({  id: string;})[];
  cloudId?: string | undefined;
  baseUrl?: string | undefined;
  timeZone?: string | undefined;
};

export interface IssueType {
  projectId: string;
  id: string;
  name: string;
  description: string | null;
  url: string;
};

export interface SyncMetadata_jira_issues {
  projectIdsToSync: ({  id: string;})[];
  cloudId?: string | undefined;
  baseUrl?: string | undefined;
  timeZone?: string | undefined;
};

export interface Issue {
  id: string;
  createdAt: string;
  updatedAt: string;
  key: string;
  summary: string;
  issueType: string;
  status: string;
  assignee: string | null;
  url: string;
  webUrl: string;
  projectId: string;
  projectKey: string;
  projectName: string;
  comments: ({  id: string;
  createdAt: string;
  updatedAt: string;
  author: {  accountId: string | null;
  active: boolean;
  displayName: string;
  emailAddress: string | null;};
  body: {};})[];
};

export interface ActionInput_jira_createissue {
  summary: string;
  description?: string | undefined;
  assignee?: string | undefined;
  labels?: string[] | undefined;
  project: string;
  issueType: string;
};

export interface ActionOutput_jira_createissue {
  id: string;
  key: string;
  self: string;
};
